import 'dart:collection';

import 'package:cloud_firestore/cloud_firestore.dart';

class Meal {
  // unique autogenerated by database
  String _id;

  String name;
  List<String> _food = [];

  Meal({this.name});

  // these methods might fit better in firebase provider
  Meal.fromSnapshot(DocumentSnapshot snapshot)
      : _id = snapshot.documentID,
        name = snapshot.data['name'],
        _food = List.from(snapshot.data['food']);

  Map<String, dynamic> toSnapshot() => {'name': name, 'food': _food};

  String get id => _id;

  UnmodifiableListView<String> get food => UnmodifiableListView(_food);

  void addFood(String food) {
    if (!_food.contains(food)) _food.add(food);
  }

  void removeFood(String food) {
    _food.remove(food);
  }

  void emptyFood() {
    _food = [];
  }

  bool isUpdate() {
    return _id != null;
  }

  static int maxFoodIngredients = 4;

  @override
  String toString() {
    return '$name -> $food';
  }
}
