import 'dart:collection';
import 'dart:convert';

import 'package:cloud_firestore/cloud_firestore.dart';

class Meal {
  // unique autogenerated by database or provider
  String _id;

  String name;
  List<String> _food = [];

  Meal({this.name});

  // these methods might fit better in the providers
  Meal.fromSnapshot(DocumentSnapshot snapshot)
      : _id = snapshot.documentID,
        name = snapshot.data['name'],
        _food = List.from(snapshot.data['food']);

  Map<String, dynamic> toSnapshot() => {'name': name, 'food': _food};

  Map<String, dynamic> toSqliteMap() {
    var foodAsString = json.encode(_food);
    var map = {'name': name, 'food': foodAsString};
    if (_id != null) map['id'] = _id;
    return map;
  }

  Meal.fromSqliteMap(Map map)
      : _id = map['id'].toString(),
        name = map['name'],
        _food = List.from(json.decode(map['food']));

  String get id => _id;

  UnmodifiableListView<String> get food => UnmodifiableListView(_food);

  void addFood(String food) {
    if (!_food.contains(food)) _food.add(food);
  }

  void removeFood(String food) {
    _food.remove(food);
  }

  void emptyFood() {
    _food = [];
  }

  bool isUpdate() {
    return _id != null;
  }

  static int maxFoodIngredients = 4;

  @override
  String toString() {
    return '$name -> $food';
  }
}
